### ISSUE TITLE
Syntax error in terms after adding Sing & Plur features

### ISSUE THREAD

**Issue by kovvalsky** [mskandalis/hybrid_nli_fr#1]
The following lines have imbalanced parentheses, missing the closing one, in 
[datasets/langpro/sick_langpro_input_prolog_0_0001.pl](https://github.com/mskandalis/hybrid_nli_fr/blob/6ad2c1ec6f994b04ca20f09d9b14d72e62437b38/datasets/langpro/sick_langpro_input_prolog_0_0001.pl)

```txt
ERROR: prove_SICK_NL/SICK_FR/sick_langpro_input_prolog.pl:35228:1223: Syntax error: Operator expected
ERROR: prove_SICK_NL/SICK_FR/sick_langpro_input_prolog.pl:35246:1223: Syntax error: Operator expected
ERROR: prove_SICK_NL/SICK_FR/sick_langpro_input_prolog.pl:36968:1225: Syntax error: Operator expected
ERROR: prove_SICK_NL/SICK_FR/sick_langpro_input_prolog.pl:36980:1225: Syntax error: Operator expected
ERROR: prove_SICK_NL/SICK_FR/sick_langpro_input_prolog.pl:38834:1995: Syntax error: Operator expected
ERROR: prove_SICK_NL/SICK_FR/sick_langpro_input_prolog.pl:38870:1995: Syntax error: Operator expected
```

One more thing: what did you change for lemmas? It seems some lemma issues are gone, e.g., previously `joue` would get `joue` as a lemma, instead of `jouer`.

```
3338:      contradiction
      Il n'y a pas d'homme debout sur un toit et jouant du violon
      Un homme est debout sur un toit et joue du violon
```

**Comment by mskandalis** [comment]
> The following lines have imbalanced parentheses, missing the closing one, in [datasets/langpro/sick_langpro_input_prolog_0_0001.pl](https://github.com/mskandalis/hybrid_nli_fr/blob/6ad2c1ec6f994b04ca20f09d9b14d72e62437b38/datasets/langpro/sick_langpro_input_prolog_0_0001.pl)
> 
> ERROR: prove_SICK_NL/SICK_FR/sick_langpro_input_prolog.pl:35228:1223: Syntax error: Operator expected
> ERROR: prove_SICK_NL/SICK_FR/sick_langpro_input_prolog.pl:35246:1223: Syntax error: Operator expected
> ERROR: prove_SICK_NL/SICK_FR/sick_langpro_input_prolog.pl:36968:1225: Syntax error: Operator expected
> ERROR: prove_SICK_NL/SICK_FR/sick_langpro_input_prolog.pl:36980:1225: Syntax error: Operator expected
> ERROR: prove_SICK_NL/SICK_FR/sick_langpro_input_prolog.pl:38834:1995: Syntax error: Operator expected
> ERROR: prove_SICK_NL/SICK_FR/sick_langpro_input_prolog.pl:38870:1995: Syntax error: Operator expected

There are several improvements in this file.

I implemented Clark and Curran's beta-value assignment in the Transformer version of Moot's DeepGrail CG Supertagger. As a result, the success rate in proof generation by Graillight increased from 92.96% (1,386 failed sentences) to 99.82% (only 36 failed sentences) for SICK-FR.

These six examples (actually three sentences, each occurring twice) were parsed by Graillight, but incorrectly (previously, without the beta-value set, no proof had been generated for them at all). I believe we can consider these six defective—the unmatched parentheses occur because there is an issue with their proofs from the previous step, such as a variable disappearing when traversing down the proof tree (so we lose its type information), or some words application order changing inconsistently along the tree.

> One more thing: what did you change for lemmas? It seems some lemma issues are gone, e.g., previously `joue` would get `joue` as a lemma, instead of `jouer`.
> 
> ```
> 3338:      contradiction
>       Il n'y a pas d'homme debout sur un toit et jouant du violon
>       Un homme est debout sur un toit et joue du violon
> ```

I replaced spaCy’s lemmas with those from Stanza. After inspecting their outputs, Stanza’s lemmas seemed to me more accurate for French.

**Comment by kovvalsky** [comment]
Thanks. I added parentheses manually to those trees to silence the error reports. But as you said, they still won't lead to any proofs as they are faulty.
